Vagrant.configure("2") do |config|
  config.vm.box = "rosevm/xubuntu"
  config.vm.box_url = "http://swift.cloud.garr.it/swift/v1/rose/vm/rosevm-xubuntu.box"
  config.vm.base_mac = "080027A21F69"
  config.vm.provider "virtualbox" do |v|
    v.name = "rose-srv6"
  end
end
